<html>
<head><meta charset="utf-8"><title>wasmtime / issue #11486 Exceptions: support Pulley · git-wasmtime · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/index.html">git-wasmtime</a></h2>
<h3>Topic: <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2311486.20Exceptions.3A.20support.20Pulley.html">wasmtime / issue #11486 Exceptions: support Pulley</a></h3>

<hr>

<base href="https://bytecodealliance.zulipchat.com">

<head><link href="https://bytecodealliance.github.io/zulip-archive/style.css" rel="stylesheet"></head>

<a name="535416775"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20issue%20%2311486%20Exceptions%3A%20support%20Pulley/near/535416775" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2311486.20Exceptions.3A.20support.20Pulley.html#535416775">(Aug 21 2025 at 02:17)</a>:</h4>
<p>cfallin opened <a href="https://github.com/bytecodealliance/wasmtime/issues/11486">issue #11486</a>:</p>
<blockquote>
<p>The exception-handling support as implemented in #11326 does not yet support Pulley. It is almost there, but not quite:</p>
<ul>
<li>Pulley's use of Cranelift for code generation means that we <em>do</em> get exception metadata alongside Pulley bytecode, and a module that uses exceptions can be <em>compiled</em>;</li>
<li>The support for stack-walking of Pulley stacks means that the exception unwinder <em>can</em> find handlers in Pulley code;</li>
<li>However, the <code>raise</code> libcall implementation that Pulley uses does not account for <code>UnwindState::UnwindToWasm</code>. This means that we'll reach host-to-Wasm entry instead, with an unexpected unwind state, and panic.</li>
</ul>
<p>In <a href="https://github.com/bytecodealliance/wasmtime/pull/11326#issuecomment-3201732110">this comment</a> I outline an alternative approach: we should</p>
<ul>
<li>invoke the real <code>raise</code> libcall, just as we do other libcalls, from Pulley;</li>
<li>when we enter <code>unwind</code>, and either <code>wasmtime_longjmp()</code> or <code>wasmtime_unwinder::resume_to_exception_handler()</code>, we instead check the store's executor and<ul>
<li>on native code, do as we do today</li>
<li>on Pulley, update the Pulley interpreter state appropriately</li>
</ul>
</li>
</ul>
</blockquote>



<a name="535416776"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20issue%20%2311486%20Exceptions%3A%20support%20Pulley/near/535416776" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2311486.20Exceptions.3A.20support.20Pulley.html#535416776">(Aug 21 2025 at 02:17)</a>:</h4>
<p><a href="https://github.com/cfallin">cfallin</a> added the pulley label to <a href="https://github.com/bytecodealliance/wasmtime/issues/11486">Issue #11486</a>.</p>



<a name="535416777"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20issue%20%2311486%20Exceptions%3A%20support%20Pulley/near/535416777" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2311486.20Exceptions.3A.20support.20Pulley.html#535416777">(Aug 21 2025 at 02:17)</a>:</h4>
<p><a href="https://github.com/cfallin">cfallin</a> added the wasm-proposal:exceptions label to <a href="https://github.com/bytecodealliance/wasmtime/issues/11486">Issue #11486</a>.</p>



<a name="535416814"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20issue%20%2311486%20Exceptions%3A%20support%20Pulley/near/535416814" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2311486.20Exceptions.3A.20support.20Pulley.html#535416814">(Aug 21 2025 at 02:17)</a>:</h4>
<p>github-actions[bot] <a href="https://github.com/bytecodealliance/wasmtime/issues/11486#issuecomment-3208753504">commented</a> on <a href="https://github.com/bytecodealliance/wasmtime/issues/11486">issue #11486</a>:</p>
<blockquote>
<h4>Subscribe to Label Action</h4>
<p>cc @fitzgen</p>
<p>&lt;details&gt;<br>
This issue or pull request has been labeled: "pulley"</p>
<p>Thus the following users have been cc'd because of the following labels:</p>
<ul>
<li>fitzgen: pulley</li>
</ul>
<p>To subscribe or unsubscribe from this label, edit the &lt;code&gt;.github/subscribe-to-label.json&lt;/code&gt; configuration file.</p>
<p><a href="https://github.com/bytecodealliance/subscribe-to-label-action">Learn more.</a><br>
&lt;/details&gt;</p>
</blockquote>



<a name="535588972"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20issue%20%2311486%20Exceptions%3A%20support%20Pulley/near/535588972" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2311486.20Exceptions.3A.20support.20Pulley.html#535588972">(Aug 21 2025 at 22:42)</a>:</h4>
<p>alexcrichton closed <a href="https://github.com/bytecodealliance/wasmtime/issues/11486">issue #11486</a>:</p>
<blockquote>
<p>The exception-handling support as implemented in #11326 does not yet support Pulley. It is almost there, but not quite:</p>
<ul>
<li>Pulley's use of Cranelift for code generation means that we <em>do</em> get exception metadata alongside Pulley bytecode, and a module that uses exceptions can be <em>compiled</em>;</li>
<li>The support for stack-walking of Pulley stacks means that the exception unwinder <em>can</em> find handlers in Pulley code;</li>
<li>However, the <code>raise</code> libcall implementation that Pulley uses does not account for <code>UnwindState::UnwindToWasm</code>. This means that we'll reach host-to-Wasm entry instead, with an unexpected unwind state, and panic.</li>
</ul>
<p>In <a href="https://github.com/bytecodealliance/wasmtime/pull/11326#issuecomment-3201732110">this comment</a> I outline an alternative approach: we should</p>
<ul>
<li>invoke the real <code>raise</code> libcall, just as we do other libcalls, from Pulley;</li>
<li>when we enter <code>unwind</code>, and either <code>wasmtime_longjmp()</code> or <code>wasmtime_unwinder::resume_to_exception_handler()</code>, we instead check the store's executor and<ul>
<li>on native code, do as we do today</li>
<li>on Pulley, update the Pulley interpreter state appropriately</li>
</ul>
</li>
</ul>
</blockquote>



<hr><p>Last updated: Oct 25 2025 at 23:03 UTC</p>
</html>